use_frameworks!

target 'NotesExample-iOS' do
  platform :ios, :deployment_target => '11.0'
  pod 'ObjectBox', :path => '../'
  pod 'Sourcery'
end

target 'NotesExample-macOS' do
  platform :osx, :deployment_target => '10.10'
  pod 'ObjectBox', :path => '../'
  pod 'Sourcery'
end
