/*
 * Copyright 2020 ObjectBox Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all



///  Basic type of a property
public enum PropertyType: UInt16 {
    public typealias T = UInt16
    public static var byteSize: Int { return MemoryLayout<UInt16>.size }
    public var value: UInt16 { return self.rawValue }
    ///  Not a real type, just best practice (e.g. forward compatibility)
    case unknown = 0
    case bool = 1
    case byte = 2
    case short = 3
    case char = 4
    case int = 5
    case long = 6
    case float = 7
    case double = 8
    case string = 9
    ///  Date/time stored as a 64 bit long representing milliseconds since 1970-01-01 (unix epoch)
    case date = 10
    ///  Relation to another entity
    case relation = 11
    ///  High precision date/time stored as a 64 bit long representing nanoseconds since 1970-01-01 (unix epoch)
    case datenano = 12
    case reserved2 = 13
    case reserved3 = 14
    case reserved4 = 15
    case reserved5 = 16
    case reserved6 = 17
    case reserved7 = 18
    case reserved8 = 19
    case reserved9 = 20
    case reserved10 = 21
    case boolVector = 22
    case byteVector = 23
    case shortVector = 24
    case charVector = 25
    case intVector = 26
    case longVector = 27
    case floatVector = 28
    case doubleVector = 29
    case stringVector = 30
    case dateVector = 31
    case dateNanoVector = 32
    

    public static var max: PropertyType { return .dateNanoVector }
    public static var min: PropertyType { return .unknown }
}

///  Bit-flags defining the behavior of properties.
///  Note: Numbers indicate the bit position
public enum PropertyFlags: UInt32 {
    public typealias T = UInt32
    public static var byteSize: Int { return MemoryLayout<UInt32>.size }
    public var value: UInt32 { return self.rawValue }
    ///  64 bit long property (internally unsigned) representing the ID of the entity.
    ///  May be combined with: NON_PRIMITIVE_TYPE, ID_MONOTONIC_SEQUENCE, ID_SELF_ASSIGNABLE.
    case id = 1
    ///  On languages like Java, a non-primitive type is used (aka wrapper types, allowing null)
    case nonPrimitiveType = 2
    ///  Unused yet
    case notNull = 4
    case indexed = 8
    ///  Unused yet
    case reserved = 16
    ///  Unique index
    case unique = 32
    ///  Unused yet: Use a persisted sequence to enforce ID to rise monotonic (no ID reuse)
    case idMonotonicSequence = 64
    ///  Allow IDs to be assigned by the developer
    case idSelfAssignable = 128
    ///  Unused yet
    case indexPartialSkipNull = 256
    ///  Unused yet in user land.
    ///  Used internally by relations for 1) backlinks and 2) to clear references to deleted objects (required for ID reuse).
    case indexPartialSkipZero = 512
    ///  Virtual properties may not have a dedicated field in their entity class, e.g. target IDs of to-one relations
    case virtual = 1024
    ///  Index uses a 32 bit hash instead of the value. 32 bit is the default hash size because:
    ///  they take less disk space, run well on 32 bit systems, and also run quite well on 64 bit systems
    ///  (especially for small to medium sized values).
    ///  and should be OK even with a few collisions.
    case indexHash = 2048
    ///  Index uses a 64 bit hash instead of the value.
    ///  Recommended mostly for 64 bit machines with values longer than 200 bytes;
    ///  small values are faster with a 32 bit hash even on 64 bit machines.
    case indexHash64 = 4096
    ///  Unused yet: While our default are signed ints, queries and indexes need do know signing info.
    ///  Note: Don't combine with ID (IDs are always unsigned internally).
    case unsigned = 8192
    ///  By defining an ID companion property, a special ID encoding scheme is activated involving this property.
    /// 
    ///  For Time Series IDs, a companion property of type Date or DateNano represents the exact timestamp.
    ///  (In the future, ID companion string properties may be added as another supported type).
    case idCompanion = 16384
    

    public static var max: PropertyFlags { return .idCompanion }
    public static var min: PropertyFlags { return .id }
}


extension Array where Element == PropertyFlags {
    var rawValue: UInt32 {
        var combined: UInt32 = 0
        for value in self {
            combined |= value.rawValue
        }
        return combined
    }
}
