// swift-tools-version:5.7
// WARNING This file is generated by ios-framework/cocoapod/make-release.command

import PackageDescription

let package = Package(
    name: "ObjectBox",
    platforms: [
        .macOS(.v10_15), .iOS(.v12)
    ],
    products: [
        .library(
            name: "ObjectBox",
            targets: ["ObjectBox"]),
    ],
    targets: [
        .binaryTarget(
            name: "ObjectBox",
            url: "https://github.com/objectbox/objectbox-swift/releases/download/v4.0.1/ObjectBox-xcframework-4.0.1.zip",
            checksum: "02a0f686ced7488a9afe312e3b1a7cac634848709bd04cd904a3a5fa26ec8d31"
        )
    ]
)

