// swift-tools-version:5.7
// WARNING This file is generated by ios-framework/cocoapod/make-release.command

import PackageDescription

let package = Package(
    name: "ObjectBox",
    platforms: [
        .macOS(.v10_15), .iOS(.v12)
    ],
    products: [
        .library(
            name: "ObjectBox",
            targets: ["ObjectBox"]),
    ],
    targets: [
        .binaryTarget(
            name: "ObjectBox",
            url: "https://github.com/objectbox/objectbox-swift/releases/download/v1.9.2/ObjectBox-xcframework-1.9.2.zip",
            checksum: "e70e580fe40ef752fbb29b4cb0a3be1c51f3024020bf1832a73e79e921b42dd3"
        )
    ]
)

