// swift-tools-version:5.7
// WARNING This file is generated by ios-framework/cocoapod/make-release.command

import PackageDescription

let package = Package(
    name: "ObjectBox",
    platforms: [
        .macOS(.v10_15), .iOS(.v12)
    ],
    products: [
        .library(
            name: "ObjectBox",
            targets: ["ObjectBox"]),
    ],
    targets: [
        .binaryTarget(
            name: "ObjectBox",
            url: "https://github.com/objectbox/objectbox-swift/releases/download/v4.0.0/ObjectBox-xcframework-4.0.0.zip",
            checksum: "2bed7b8b87dd46dda64fa1f5e7a0b1df87908a783690fda09c6dc943a01a32e5"
        )
    ]
)

