included:
    - CommonSource
    - CommonTests
    - ObjectBox-macOS/ObjectBox
    - ObjectBox-macOS/ObjectBoxTests
line_length: 120
reporter: "xcode"
disabled_rules:
    - file_length
    - trailing_whitespace
    - todo
    - vertical_whitespace
identifier_name:
    excluded:
        - id
        - ok
        - tx
type_name:
    excluded:
        - Id
        - __EntityRelatable # TODO check this one; can we remove it altogether?
